Option Explicit
On Error Resume Next

Dim DateC, DB, WSO, WS, RS, strvar, TS, i, j
Dim xlApp


Const ForReading = 1
Const ForWriting = 2
Const ForAppending = 8
Const adOpenStatic = 3
Const adLockOptimistic = 3 
 
DateC = Date()-1 

Set DB = CreateObject("ADODB.Connection")
		
DB.Open "Provider=Microsoft.ACE.OLEDB.12.0; Data Source=E:\Mconnect Plus\MConnect_Plus.accdb;"


Set RS = DB.Execute("SELECT SBCAODSS as SUCCESS, SBCAODTD as TECHNICALD, SBCAODBD as BUSINESSD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT PPFSS, PPFTD, PPFBD FROM DAILY_MIS where DATEF = '"&DateC&"'UNION ALL SELECT LOANSS, LOANTD, LOANBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT SSFTSS, SSFTTD, SSFTBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT TPFTSS, TPFTTD, TPFTBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT IMPSSS, IMPSTDREM,IMPSBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT NEFTSS, NEFTTD, NEFTBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT MRECHARGESS, MRECHARGETD, MRECHARGEBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT BBPSDRECHARGESS, BBPSDRECHARGETD, BBPSDRECHARGEBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT NBBPSDRECHARGESS, NBBPSDRECHARGETD, NBBPSDRECHARGEBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT REGBILLPAYSS, REGBILLPAYTD, REGBILLPAYBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT QBILLPAYSS, QBILLPAYTD, QBILLPAYBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT TBBPSPAYSS, TBBPSPAYTD, TBBPSPAYBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT CCPAYSS, CCPAYTD, CCPAYBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT FDOPENSS, FDOPENTD, FDOPENBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT RDOPENSS, RDOPENTD, RDOPENBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT STPAYSS, STPAYTD, STPAYBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT COMI, COMTD, COMBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT TTSS, TTTD, TTBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT PMJJBYSS, PMJJBYTD, PMJJBYBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT PMSBYSS, PMSBYTD, PMSBYBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT MYACCSS, MYACCTD, MYACCBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT ACCDETSS, ACCDETTD, ACCDETBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT MINISSS, MINISTD, MINISBD FROM DAILY_MIS where  DATEF = '"&DateC&"' UNION ALL SELECT BINVEST,'','' FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT CBREQSS, CBREQTD, CBREQBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT CHSTATSS, CHSTATTD, CHSTATBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT STOPCHQSS, STOPCHQTD, STOPCHQBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT AADHARSS, AADHARTD, AADHARBD FROM DAILY_MIS  where DATEF = '"&DateC&"' UNION ALL SELECT ACCSTATSS, ACCSTATTD, ACCSTATBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT INTCERTSS, INTCERTTD, INTCERTBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT DCHOTSS, DCHOTTD, DCHOTBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT TDSCERTSS, TDSCERTTD, TDSCERTBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT FORM15SS, FORM15TD, FORM15BD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT NOMISS, NOMITD, NOMIBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT DCREQSS, DCREQTD, DCREQBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT ACCTFRSS, ACCTFRTD, ACCTFRBD FROM DAILY_MIS where  DATEF = '"&DateC&"' UNION ALL SELECT FDRDCLSSS, FDRDCLSTD, FDRDCLSBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT SSASS, SSATD, SSABD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT DGPSS, DGPTD, DGPBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT IBREGSS, IBREGTD, IBREGBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT IBPWDSS, IBPWDTD, IBPWDBD FROM DAILY_MIS where DATEF = '"&DateC&"' UNION ALL SELECT COMAILSS, COMAILTD, COMAILBD FROM DAILY_MIS where DATEF = '"&DateC&"'")


Set xlApp = CreateObject("Excel.Application")
xlApp.Workbooks.Open("E:\Mconnect Plus\MIS\"&DateC&".xlsx")

Set TS = xlApp.ActiveWorkbook.Worksheets("Sample")

j = 13
DO WHILE i<21
TS.Cells(j,3).Value = ""&RS.Fields(0)&""
TS.Cells(j,4).Value = ""&RS.Fields(1)&""
TS.Cells(j,5).Value = ""&RS.Fields(2)&""
RS.MoveNext
i = i+1
j = j+1
Loop

Set j = Nothing
Set i = Nothing

i = 1
j = 13
DO WHILE i<22
TS.Cells(j,11).Value = ""&RS.Fields(0)&""
TS.Cells(j,12).Value = ""&RS.Fields(1)&""
TS.Cells(j,13).Value = ""&RS.Fields(2)&""
RS.MoveNext
i = i+1
j = j+1
Loop



RS.Close
DB.Close

xlApp.ActiveWorkbook.Save
xlApp.ActiveWorkbook.Close
xlApp.Application.Quit
		
		
Set xlApp = Nothing
Set xlBook = Nothing
Set xlSheet = Nothing
Set TS = Nothing

Set RS = Nothing
Set strVar = Nothing
Set DB = Nothing
